deps: Run `pod update sqlite3` to resolve `pod install` error
In f28dd0bfcb, we upgraded the Dart package sqlite3_flutter_libs
past simolus3/sqlite3.dart@c16721003, which bumped the version of
the `sqlite3` pod published on CocoaPods (not to be confused with
the Dart package with that same name on pub.dev).

So in `flutter run` targeting an iOS device, the `pod install` step
would fail with output including the following:

```
    [!] CocoaPods could not find compatible versions for pod "sqlite3":
      In snapshot (Podfile.lock):
        sqlite3 (= 3.41.0, ~> 3.41.0)

      In Podfile:
        sqlite3_flutter_libs (from `.symlinks/plugins/sqlite3_flutter_libs/ios`) was resolved to 0.0.1, which depends on
          sqlite3 (~> 3.41.2)

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `sqlite3` inside your development pod `sqlite3_flutter_libs`.
       You should run `pod update sqlite3` to apply changes you've made.
```

Flutter then gave its own output, along the lines of just that first
bullet point:

```
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Exception: Error running pod install
```

But actually, after studying both bullet points and trying their
suggested fixes, it turns out the second one is right. So, follow it
here by running `pod update sqlite3`.

(Because I wrote this commit in my environment, the command also
made a few unrelated changes that match changes that `pod install`
has been wanting to make for me recently. I'll commit those changes
separately, with an explanation, next.)