deps: Upgrade watcher
With a recent Dart SDK from Flutter main, this is required in
order for build_runner to work.  Otherwise it gives an error
like (reformatted):

    Failed to build build_runner:build_runner:
    ../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57:
      Error: The class 'FileSystemEvent' can't be extended, implemented,
      or mixed in outside of its library because it's a sealed class.
    abstract class _ConstructableFileSystemEvent implements FileSystemEvent {