content test: Skip source-file-reading test on Windows
This fails there, or at least does in the `flutter/tests` CI
environment, with an error like:

    ::group::❌ C:/Users/RUNNER~1/AppData/Local/Temp/flutter_customer_testing.zulip.4a7c3de6/tests/test/model/content_test.dart: all content examples are tested (failed)
    FileSystemException: Cannot open file, path = '/C:/Users/RUNNER~1/AppData/Local/Temp/flutter_customer_testing.zulip.4a7c3de6/tests/test/model/content_test.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
    , errno = 123)
    dart:io                               _File.readAsStringSync
    test\model\content_test.dart 1082:39  main.<fn>
    ::endgroup::

I'm not sure what's wrong, but don't really feel like finding out
(or working out how to fix it) -- and, conveniently, there's really
no need to do so.  See comment.